### ISSUE TITLE
more info on running this on own servers and packets cloud and edge

### ISSUE THREAD

**Issue by gedw99** [packet-labs/packet-k3s#1]
could you add more newbie info about how to really do this ?

I am very interested in this for our different projects.

**Comment by jmarhee** [comment]
Thank you for your interest--I've updated the documentation to further clarify the tooling and how to deploy/manage clusters in this project. I will be adding more as work continues, however, let me know if this has clarified for you somewhat.

Thanks again.

**Comment by jmarhee** [comment]
I'm going to go ahead and close this issue, but if you have any further questions, please feel free to reach out in a new issue, on the Packet Community slack, or via email (joseph at packet). Thanks!
